FROM golang:alpine3.11

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>" \
  org.label-schema.name="ownCloud CI Antora" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

ARG BOILR_REPO=github.com/tmrts/boilr
ARG GOBIN=/bin

RUN apk update && \
    apk upgrade && \
    apk add git && \
    go get "${BOILR_REPO}" && \
    go install "${BOILR_REPO}" && \
    rm -rf /var/cache/apk/*

COPY ./rootfs /
CMD []
ENTRYPOINT ["/bin/boilr"]
